### ISSUE TITLE
Con you share the files that construct the robust_CIFAR

### ISSUE THREAD

**Issue by Yingdong-Hu** [MadryLab/constructed-datasets#5]
I re-implemented the testing results of the model trained with robust_CIFAR Dataset you provide on the gihub. Then I want to construct the robust_CIFAR myself. I follow the pseudocode in Appendix C. But it seems that something goes wrong. I tried many times but coundn't reimplement the dataset. Con you share the files that construct the robust_CIFAR?

**Comment by andrewilyas** [comment]
Hi, the core of the code for making robust CIFAR can be found here: 

https://github.com/MadryLab/robust_representations/blob/master/image_inversion.ipynb

the `x_adv` variable at the end of this notebook exactly contains the "robust" versions of the CIFAR images.

**Comment by Yingdong-Hu** [comment]
Thank you for your help

**Comment by ahadda5** [comment]
> Hi, the core of the code for making robust CIFAR can be found here:
> 
> https://github.com/MadryLab/robust_representations/blob/master/image_inversion.ipynb
> 
> the `x_adv` variable at the end of this notebook exactly contains the "robust" versions of the CIFAR images.

The model object retrieved by robustness-library can only run on "manageable" batch sizes(128 , maybe 500 if your lucky)  that is on 32 GB Ram NVIDIA QUADRO RTX 6000.  (128 GB RAM , Intel Xeon Silver 4215)
What i do is move it to GPU in batch sizes, and construct a TensorDataset,in cpu, on the overall training set (say 60k or 90k whatever the size e.g. FashionMNIST, CINIC etc..)  I found that an east way to use the "robust" dataset.
